name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
      - feat/deploy

jobs:
  # 1. build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load .env and export variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          source .env
          echo "SSH_HOST=$SSH_HOST" >> $GITHUB_ENV
          echo "SSH_PORT=$SSH_PORT" >> $GITHUB_ENV
          echo "SSH_USER=$SSH_USER" >> $GITHUB_ENV
          echo "$SSH_KEY_BASE64" | base64 -d > private_key
          chmod 600 private_key

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR File
        run: |
          mvn clean package -DskipTests

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar


  # 2. docker build & push job
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-file

      - name: Build and Push Docker Image
        run: |
          mkdir -p target
          mv *.jar target/
          echo "${{ secrets.ENV_FILE }}" > .env
          source .env
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t $DOCKER_USERNAME/whenwhen:latest .
          docker push $DOCKER_USERNAME/whenwhen:latest


  # 3. deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Load .env and export variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          source .env
          echo "SSH_HOST=$SSH_HOST" >> $GITHUB_ENV
          echo "SSH_PORT=$SSH_PORT" >> $GITHUB_ENV
          echo "SSH_USER=$SSH_USER" >> $GITHUB_ENV
          echo "$SSH_KEY_BASE64" | base64 -d > private_key
          chmod 600 private_key

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          port: ${{ env.SSH_PORT }}
          username: ${{ env.SSH_USER }}
          key_path: private_key
          script: |
            echo "${{ secrets.ENV_FILE }}" > .env
            source .env
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker pull $DOCKER_USERNAME/whenwhen:latest
            docker stop whenwhen-container || true
            docker rm whenwhen-container || true
            docker run -d \
              -p 8080:8080 \
              --name whenwhen-container \
              --env-file .env \
              "$DOCKER_USERNAME/whenwhen:latest"
            rm -f .env