name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # .env 파일 생성 및 환경변수 설정
      - name: Create .env file and load variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          grep -v "EC2_KEY" .env | xargs -0 export
          grep "EC2_KEY" .env | cut -d '=' -f2- > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: ☕️ set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR File
        run: mvn clean package -DskipTests

      - name: Build and Push Docker Image
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t $DOCKER_USERNAME/whenwhen:latest .
          docker push $DOCKER_USERNAME/whenwhen:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          ENV_CONTENT: ${{ secrets.ENV_FILE }}
        with:
          envs: ENV_CONTENT
          script: |
            echo "$ENV_CONTENT" > .env
            grep -v "EC2_KEY" .env | xargs -0 export
            sudo docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            sudo docker pull $DOCKER_USERNAME/whenwhen:latest
            sudo docker stop whenwhen-container || true
            sudo docker rm whenwhen-container || true
            sudo docker run -d \
              -p 8080:8080 \
              --name whenwhen-container \
              --env-file .env \
              "$DOCKER_USERNAME/whenwhen:latest"